version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    build:
      context: .
    expose:
      - "5432"
    ports:
      - "5432:5432"
    command:
      - /bin/sh
      - -c
      - |
          apt-get update
          apt-get upgrade -y
          apt-get clean
          rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/home/data
